### PR TITLE
add config reload

### PR DESCRIPTION
**Pull request by seema84**
add config reload

### CODE REVIEW

**Comment by xgh69** [comment]
Config is reloading, because plugin is restarting - config is reloading in onEnable() in PvpToggle plugin.

**Comment by seema84** [comment]
ok i'm confused about this info "Command /pvpadmin reload restart PvpToggle plugin, not configuration." but its ok when it is in onEnable()

**Comment by MarcinWieczorek** [comment]
@xgh69 reloads the whole plugin by Spigot's PluginManager, config loads itself when the plugin gets enabled again. Don't worry about all this @seema84. Code you commited is just an unnecessary action that has no point.

**Comment by seema84** [comment]
yes its right if you restart the whole plugin on reload - my code was a single config reload (without plugin reload)

**Comment by MarcinWieczorek** [comment]
Well, I don't know why reloading whole plugin is better than reloading the config. Ask the author.
Even though your code was a single config reload as you said, next lines still reload the whole thing.

**Pull request closed without merging**
